### ISSUE TITLE
mdl-layout__inner-container breaks fixedHeader

### ISSUE THREAD

**Issue by dantman** [tleunen/react-mdl#362]
MDL defines the following in the SASS for `.mdl-layout__header`.
```sass
    @media screen and (max-width: $layout-screen-size-threshold) {
      & {
        display: none;
      }

      .mdl-layout--fixed-header > & {
        display: flex;
      }
    }
```

However the DOM that react-mdl outputs is:
```html
<div class="... mdl-layout--fixed-header"
>
  <div class="mdl-layout__inner-container">
    <header class="mdl-layout__header">
      ...
    </header>
    <div class="mdl-layout__content">
      ...
    </div>
  </div>
</div>
```

This means that `.mdl-layout--fixed-header > &` will never apply to `<Header>` and headers will always be hidden on small screens.

**Comment by tleunen** [comment]
Hmm Do you have an example?

Here's the output I see:
```css
@media screen and (max-width: 1024px)
.mdl-layout--fixed-header > .mdl-layout__inner-container > .mdl-layout__header {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
}
```
