### ISSUE TITLE
header--seemed ?

### ISSUE THREAD

**Issue by darkyen** [tleunen/react-mdl#70]
In the material.css there is 

```css
    .mdl-layout__header--seamed {
         box-shadow: none; 
    }
```

It seems to me in the docs the mdl-layout__header--transparent has been written twice instead of mdl-layout__header-seemed for no shadow ? Maybe Add it I am also mentioning this issue on mdl page
